services:
  - type: web
    name: my-django-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn myproject.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
      - key: SECRET_KEY
        generateValue: true
